# Pandas — Missing Values & Data Type Handling

In [27]:
# Initialize

#Imports
import pandas as pd
pd.set_option("display.max_columns", None)
# Load Data
employees = pd.read_csv("../data/employees.csv")
departments = pd.read_csv("../data/departments.csv")
sales = pd.read_csv("../data/sales.csv")

In [28]:
# Simulating missing data

employees.loc[3, "salary"] = None
employees.loc[5, "department"] = None

employees.head(6)

   emp_id   name   department   salary joining_date
0       1   Amit  Engineering  80000.0   2021-06-15
1       2   Neha  Engineering  75000.0   2022-03-10
2       3   Ravi           HR  50000.0   2020-01-20
3       4  Pooja           HR      NaN   2021-11-05
4       5  Karan        Sales  60000.0   2023-02-01
5       6  Suman         None  58000.0   2022-08-18

In [29]:
# Count missing values per column

employees.isnull().sum()

emp_id          0
name            0
department      1
salary          1
joining_date    0
dtype: int64

In [30]:
# Percentage of missing values

(employees.isnull().mean() * 100).round(2)

emp_id          0.0
name            0.0
department      5.0
salary          5.0
joining_date    0.0
dtype: float64

In [31]:
#Option 1: Drop rows (dangerous)

employees_cleaned = employees.dropna()
employees_cleaned.shape

(18, 5)

In [32]:
# Option 2 - Fill with business logic - Fill salary with median (safer than mean)

employees["salary"] = employees["salary"].fillna(
    employees["salary"].median()
)
employees

    emp_id    name   department   salary joining_date
0        1    Amit  Engineering  80000.0   2021-06-15
1        2    Neha  Engineering  75000.0   2022-03-10
2        3    Ravi           HR  50000.0   2020-01-20
3        4   Pooja           HR  70000.0   2021-11-05
4        5   Karan        Sales  60000.0   2023-02-01
5        6   Suman         None  58000.0   2022-08-18
6        7   Rahul  Engineering  90000.0   2019-09-12
7        8   Anita      Finance  70000.0   2021-04-01
8        9  Vikram      Finance  72000.0   2020-12-15
9       10   Meena           HR  52000.0   2022-06-20
10      11   Arjun  Engineering  85000.0   2023-01-10
11      12   Priya        Sales  62000.0   2021-03-25
12      13  Nikhil  Engineering  78000.0   2020-07-07
13      14  Kavita           HR  54000.0   2019-02-14
14      15   Rohan        Sales  59000.0   2023-05-30
15      16  Deepak      Finance  75000.0   2022-09-09
16      17  Sunita  Engineering  82000.0   2021-12-01
17      18   Manoj           HR  51000.0   2020-10-10
18      19  Pankaj        Sales  61000.0   2022-01-15
19      20    Isha  Engineering  88000.0   2019-05-05

In [33]:
# Option 3 - Fill categorical
employees["department"] = employees["department"].fillna("Unknown")
employees

    emp_id    name   department   salary joining_date
0        1    Amit  Engineering  80000.0   2021-06-15
1        2    Neha  Engineering  75000.0   2022-03-10
2        3    Ravi           HR  50000.0   2020-01-20
3        4   Pooja           HR  70000.0   2021-11-05
4        5   Karan        Sales  60000.0   2023-02-01
5        6   Suman      Unknown  58000.0   2022-08-18
6        7   Rahul  Engineering  90000.0   2019-09-12
7        8   Anita      Finance  70000.0   2021-04-01
8        9  Vikram      Finance  72000.0   2020-12-15
9       10   Meena           HR  52000.0   2022-06-20
10      11   Arjun  Engineering  85000.0   2023-01-10
11      12   Priya        Sales  62000.0   2021-03-25
12      13  Nikhil  Engineering  78000.0   2020-07-07
13      14  Kavita           HR  54000.0   2019-02-14
14      15   Rohan        Sales  59000.0   2023-05-30
15      16  Deepak      Finance  75000.0   2022-09-09
16      17  Sunita  Engineering  82000.0   2021-12-01
17      18   Manoj           HR  51000.0   2020-10-10
18      19  Pankaj        Sales  61000.0   2022-01-15
19      20    Isha  Engineering  88000.0   2019-05-05

## Data Type Conversion

In [38]:
employees.dtypes

emp_id                   int64
name                    object
department              object
salary                 float64
joining_date    datetime64[ns]
dtype: object

In [35]:
# Convert to datetime

employees["joining_date"] = pd.to_datetime(
    employees["joining_date"],
    errors="coerce"
)

In [37]:
# Convert salary safely

employees["salary"] = pd.to_numeric(
    employees["salary"],
    errors="coerce"
)

In [40]:
#Type Validation Before Join
sales["emp_id"] = sales["emp_id"].astype(int)
employees["emp_id"] = employees["emp_id"].astype(int)